runtime: python39  # Specify the Python version
entrypoint: gunicorn -b :$PORT app:app  # Use gunicorn as the WSGI server to run your app

# Define handlers for static files (if you have any)
handlers:
- url: /static
  static_dir: static
